on:
  push:
    branches:
      - main
name: docs

permissions:
  pull-requests: write
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: taskfile.nvim
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: "main"
          branch: docs/update-docs
          commit-message: Update plugin docs
          assignees: dasvh
          reviewers: dasvh
